srcdir=/mnt/hgfs/src_kernel/openswan-latest/openswan-2.6.51.5/lib/libopenswan/
OBJDIR=OBJ.linux.x86_64
OBJDIRTOP=/mnt/hgfs/src_kernel/openswan-latest/openswan-2.6.51.5/OBJ.linux.x86_64
OSDEP=linux
BUILDENV=linux
VPATH+=${srcdir}
OPENSWANSRCDIR=/mnt/hgfs/src_kernel/openswan-latest/openswan-2.6.51.5
include ${srcdir}Makefile
